name: decimal
version: 0.3.0
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: A simple package to deal with decimal numbers
homepage: https://github.com/a14n/dart-decimal
environment:
  sdk: '>=2.0.0-dev.66.0 <2.0.0'
dependencies:
  rational: ^0.3.0
dev_dependencies:
  test: ^1.2.0
