name: decimal
version: 1.1.0
description: >
  The decimal package allows you to deal with decimal numbers without losing
  precision.
repository: https://github.com/a14n/dart-decimal
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  rational: ^1.1.0

dev_dependencies:
  test: ^1.17.2
