name: decimal
version: 0.1.4-dev
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: A simple package to deal with decimal numbers
homepage: https://github.com/a14n/dart-decimal
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  rational: ^0.1.8
dev_dependencies:
  test: ^0.12.0
