name: decimal
version: 1.0.0-nullsafety
description: >
  The decimal package allows you to deal with decimal numbers without loosing
  precision.
repository: https://github.com/a14n/dart-decimal
environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  rational: ^1.0.0-nullsafety

dev_dependencies:
  test: ^1.16.0-nullsafety.12
