name: decimal
author: "Alexandre Ardhuin <alexandre.ardhuin@gmail.com>"
homepage: https://github.com/a14n/dart-decimal
version: 0.0.4
description: A simple package to deal with decimal numbers
dev_dependencies:
  unittest: any
dependencies:
  meta: any
  rational: '>=0.0.5 <1.0.0'
